### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SuzyQuant** [WorldEnterpriseGroup/hackneyuniversity#23]
- [ ] 1. Create a Super Nova.
- [ ] 2. Call governing bodies that accredits school. Ask what it takes to get accredited.
- [ ] 3. Map out existing parameters, end goals and what goes in between.
- [ ] 4. Include in the map existing resources such as guides, websites, and writers and other pain points.
- [ ] 4. Create the Curriculum Design.
- [ ] 5. Get approved by executives.
- [ ] 6. Implement the Curriculum Design.
- [ ] 7. Get Feedback.
- [ ] 5. Optimize the design.

<hr>

References:

- https://www.designotech.com/engineering-services/six-sigma/
- https://www.pinterest.ph/pin/852517404449013481/

**Comment by SanaGhouri09** [comment]
[Roadmap for HU.md](https://github.com/WorldEnterpriseGroup/hackneyuniversity/files/10400998/Roadmap.for.HU.md)
